config/routes.rb
Rails.application.routes.draw do
  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
    @student ||= Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      flash[:success] = t('.create_success')
      redirect_to students_path
    else
      flash[:error] = 'Errorrrrr'
    end
  end

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daycare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit t(:save) %>
  </div>
<% end %>

app/views/students/edit.html.erb
<!-- <h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', students_path %> -->

app/views/students/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to t('.show'), student %></td>
        <td><%= link_to t('.edit'), edit_student_path(student) %></td>
        <td><%= link_to t('.destroy'), student, method: :delete, data: { confirm: t('.confirm_delete') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new_student'), new_student_path %>

app/views/students/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>